project:
  type: book
  output-file: "BiometrieS3"

book:
  title: "TP de Biométrie<br> Semestre 3<br>"
  author: "Benoît Simon-Bouhet"
  date: today
  search: true
  downloads: [pdf]
  repo-url: "https://github.com/besibo/BiometrieS3"
  chapters:
    - index.qmd
    - 01-R-basics.qmd
    - 02-dataset.qmd
    - 03-visualization.qmd
    - 04-DataWrangling.qmd
    - references.qmd

bibliography: all.bib
lang: fr
title-block-banner: true
language: 
  title-block-author-single: "Auteur"
  title-block-published: "Dernière Mise à jour"

format:
  html:
    theme: united
    highlight-style: solarized
    # code-tools: 
    #   source: false
    #   toggle: true
    # code-fold: show
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    smooth-scroll: true

  # pdf:
  #   documentclass: scrreprt



